char	*sys_errlist[] = {
	"Error 0",
	"Not owner",
	"No such file or directory",
	"No such process",
	"Interrupted system call",
	"I/O error",
	"No such device or address",
	"Arg list too long",
	"Exec format error",
	"Bad file number",
	"No children",
	"No more processes",
	"Not enough core",
	"Permission denied",
	"Bad address",
	"Block device required",
	"Mount device busy",
	"File exists",
	"Cross-device link",
	"No such device",
	"Not a directory",
	"Is a directory",
	"Invalid argument",
	"File table overflow",
	"Too many open files",
	"Not a typewriter",
	"Text file busy",
	"File too large",
	"No space left on device",
	"Illegal seek",
	"Read-only file system",
	"Too many links",
	"Broken pipe",
	"Argument too large",
	"Result too large",
	"Network status (not an error)",
	"Network not available",
	"Too many connections",
	"Out of net buffers",
	"Bad net open mode or ioctl type",
	"Bad local address, port, link, or protocol",
	"Destination dead",
	"Raw message send failed",
	"Read or write on closed connection",
	"Destination refused",
	"Destination unreachable",
	"Destination not responding (timeout)"
};
int	sys_nerr = { sizeof sys_errlist/sizeof sys_errlist[0] };
